### ISSUE TITLE
Social logins return 404

### ISSUE THREAD

**Issue by danielvanc** [arpitdalal/remix-supabase-auth#1]
Hey, I recently cloned your repo and set it up with the instructions provided, but when i click on either google / facebook login, i get the below error.

![Screenshot 2022-03-15 at 17 02 52](https://user-images.githubusercontent.com/310698/158432771-bca0a665-3642-4b92-ba73-f029e5ba8717.png)

The url after you click the google button is: `http://localhost:3000/=https://<my-supabase-url>.supabase.co/auth/v1/authorize?provider=google&redirect_to=http%3A%2F%2Flocalhost%3A3000%2Fprofile`

**Comment by arpitdalal** [comment]
Hey @danielvanc
I have been working on a better version of this example which will be out shortly. I'll advise you to use that version as this has a security flaw.
To fix the current issue, I think your Supabase project is redirecting to the base URL instead of `localhost:3000/profile` and you'll need to add the **exact** URL: `http://localhost:3000/profile` in the "Aditional Redirect URLs" textbox inside the page `https://app.supabase.io/project/<your-project-id>/auth/settings` or going to Authentication > Settings under Configuration

Edit: The new version omits the step where you need to specify the URL in that textbox

**Comment by danielvanc** [comment]
Hey @arpitdalal,
Thanks for getting back so quickly! I have changed those settings in my Supabase project but it still didn't work? If the new version won't need that configuration, i can wait until then. Do you have a time frame on when that might be available?

Kind regards,

**Comment by arpitdalal** [comment]
[v2](https://github.com/arpitdalal/remix-supabase-auth) on `main` is available, still need to work on `js` branch for v2. If you prefer `js`, you can clone the `main` branch and strip off all the types and rename files.
If you still face this issue, can you please create a reproducible example because I am not able to reproduce this on my end. And if you don't face any issues, please feel free to close this issue.
Here are my Supabase settings: ![image](https://user-images.githubusercontent.com/61059807/158481744-740a7b0a-8a37-4281-92fa-fcd8179a4a76.png)

**Comment by danielvanc** [comment]
Thank you for updating @arpitdalal. This now works for me 👍🏼
